#!/bin/bash

###############################################################
# print value(s) of csh variables
#

if [ -z "$2" ]; then
	echo "Usage: csh2bash <csh source file> <variable>"
	exit 0
fi
src=$1
var=$2
if [ ! -f "$src" ]; then
	exit 1
fi

srch="set $var"
str=`grep "$srch" $src | tail -1`
str=${str#*=}
str=${str%#*}
str=${str//(/""}
str=( ${str//)/""} )

echo "${str[*]}"


