#!/bin/bash

#Sun Grid Engine configuration options
#shell name
#$ -S /bin/bash
#write .e and .o to the working directory
#$ -cwd
#merge stdout and stderr
#$ -j y
#import environment variables
#$ -V

# in 1: downloaded study location
# in 2: location to save file with mappings
# in 3: predefined scans
function save_UID_map
{
	local st=$1 
	local mf=$2
	local sc=($3)
	
	pushd $st/scans &> /dev/null
	local scans=""
	local uids=""
	local scan xnatid suid i j found
	for ((i=0; i<${#sc[*]}; i++)); do
		scandir=(`ls -d ${sc[i]}-*`)
		if [ -z "${scandir}" ]; then
			echo "xnat2loc ERROR: cannot find scan ${sc[i]}, exiting"
			exit -1
		fi
		if (( ${#scandir[*]} > 1 )); then
			regex="${sc[i]}-MR([0-9]+).*"
			found=-1
			for (( j=0; j<${#scandir[*]}; j++ )); do
				[[ "${scandir[j]}" =~ $regex ]]
				if [ -z "${BASH_REMATCH[0]}" ]; then
					if (( found != -1 )); then
						echo "xnat2loc ERROR: cannot uniquely resolve scan ID: ${sc[i]}, exiting"
						exit -1
					else
						found=$j
					fi
				fi
			done
			scandir=${scandir[found]}
			if [ -z "${scandir}" -o "$found" == "-1" ]; then
				echo "xnat2loc ERROR: cannot find scan ${sc[i]}, exiting"
				exit -1
			fi
		fi
		xnatid=${scan%-*}
		suid=(`dcminfo -q -t 0020 000e $scandir/resources/DICOM/files`)
		suid=( $suid )
		suid=`echo $suid | tr -d '<>'`
#		scans="$scans ${sc[i]}"
		if ((i>0)); then
			uids="$uids,${sc[i]},$suid"
		else
			uids="${sc[i]},$suid"
		fi
	done
	popd &> /dev/null
	echo "serinstuids=($uids)" | tr -d ' ' >> $mf
}

function exit_with_error
{
    echo "xnat2loc ERROR: $1, exiting"
    exit -1
}

#1: str
#2: field
function get_field
{
	local b="$1" f="$2" c d
	c=${b# * ID=\"}
	d=${c%%\"*}
}

###################################################################
#
# Get scan #'s of given types.
# 
# input 1: CURL connection string, i.e. curl -k -u user:pass host ....
# input 2: scan type
#

function get_scans
{
	local cstr="$1"
	local stypes="$2"
	local line id scans

	local f=`mktemp xnat2locXXXX` f1=`mktemp xnat2locXXXX`
	$cstr > $f
	grep "xnat:scan ID=.*type=\"$2\"" $f > $f1
	while read line; do
		c=${line#* ID=\"};id=${c%%\"*}
		if [ -n "$scans" ]; then scans="$id,$scans"; else scans=$id; fi
	done < $f1
	echo $scans
}

#split tokenized string 
#input 1: string
#input 2: token
function split_str
{
	local str="$1"
	local token="$2"
	arr=`echo "$str" | tr "$token" " "`
	echo $arr
}
echo "XNAT session -> local storage"
if [ -z $1 ]; then
	echo "Usage: xnat2loc <session label> [options]"
	echo "Options:"
	echo "	-sr	<server>			"
	echo "	-u	<user>"
	echo "	-pa	<password>"
	echo "	-js	<JSESSIONID>"
	echo "	-pr	<XNAT project>"
	echo "	-o	<outdir>			"
	echo "	-s	<scan_id>[,<scan_id>,...]	scan ids (default is ALL)"
	echo "	-m	save XNAT ID -> DICOM Series instance UID map to scans.txt"
	echo "	-st	<scan_type>	scan type"
	echo "	-r	<dir>[,<dir>,...]		resource directory(ies) to download"
	echo "	-subj	<subject ID>"
	echo "	-z	Do not unzip"
	echo "	-uncompress	uncompress incoming DICOM scans."
	echo "	-rm_enh	remove enhanced MRI from downloaded DICOM's"
	echo "NOTE: if both -s and -r are specified, specified scans with specified scan resource dir(s) will be downloaded."
	exit -1
fi
umask 0007
dcmsrt=${MFREL}/dcm_sort
dcmsrt=dcm_sort

slabel=$1; shift;

for arg in "$@"; do args[i]=$arg; ((i++)); done
#for((i=1; i<((${#args[*]})); i++)); do echo ${args[i]}; done
mapfile=0; uncompress=0; rm_enh=0
#set -x

JSESSION=""

while [ -n "$1" ]; do
	case "$1" in
		-sr) shift; server=$1; shift ;;
		 -z) shift; savezip=1 ;;
		 -u) shift; user=$1; shift ;;
		-pa) shift; pass=$1; shift ;;
		-js) shift; JSESSION=$1; shift ;;
		 -l) shift; slabel=$1; shift ;;
		-pr) shift; project=$1; shift ;;
		-sr) shift; server=$1; shift ;;
		 -o) shift; outdir=$1; shift ;;
		 -m) shift; mapfile=1; shift ;;
		 -s) shift; scans=$1; shift; if [ -f "$scans" ]; then scans=`cat $scans`; fi ;;
		-st) shift; stypes=$1; shift; if [ -f "$stypes" ]; then stypes=`cat $stypes`; fi ;;
		 -r) shift; rdirs=$1; shift; if [ -f "$rdirs" ]; then stypes=`cat $rdirs`; fi ;;
		 -rm_enh) shift; rm_enh=1 ;;
	  -subj) shift; subj=$1; shift ;;
-uncompress) shift; uncompress=1 ;;
		  *) shift ;;
	esac
done

server=`echo $server | sed 's/\/$//'`
if [ -z "$project" -o -z "$subj" -o -z "$slabel" ]; then
    exit_with_error "Please specify project, subject and session label."
fi

if [ -z "$JSESSION" ]; then
	if [ -z "$user" -o -z "$pass" ]; then exit_with_error "User credentials required"; fi
	echo curl -s -k -u $user:xxxx "$server/data/JSESSION"
	JSESSION=`curl -s -k -u $user:$pass "$server/data/JSESSION"`
	JSERROR=`echo $JSESSION | grep Error`
	if [ -n "$JSERROR" ]; then exit_with_error "user credentials failed"; fi
fi
prm="curl -k --cookie JSESSIONID=$JSESSION"; prms="curl -k --cookie JSESSIONID=[...]"; 
echo "JSESSION: $JSESSION"
#scan resource dir with DICOM files.
dcmdir=DICOM
#uncomment for modified DICOM
#dcmdir=DICOM_ORIG

echo "project: $project subject: $subj session: $slabel scans: $scans"
if [ -z "$outdir" ]; then outdir=$slabel; fi
mkdir $outdir; pushd $outdir &> /dev/null

if [ -n "$stypes" ]; then
	cstr="$prm $server/REST/projects/$project/subjects/$subj/experiments/$slabel?format=xml"
	extra_scans=`get_scans "$cstr" "$stypes"`
	if [ -z "$scans" ]; then 
		scans=$extra_scans
	else
		scans="${scans},$extra_scans"
	fi
elif [ -z "$scans" ]; then 
	scans="ALL"; 
fi

#download scans if no resource dir was specified
if [ -n "$scans" -a -z "$rdirs" ]; then
	echo "$prms \"${server}/REST/projects/${project}/subjects/${subj}/experiments/${slabel}/scans/${scans}/files?format=zip\""
	$prm "${server}/REST/projects/${project}/subjects/${subj}/experiments/${slabel}/scans/${scans}/files?format=zip" > temp.zip
#download resource dir(s)
	if [ -n "$savezip" ]; then popd &> /dev/null; exit 0; fi
	unzip temp.zip &> /dev/null; rm temp.zip
	mkdir DICOM
#	mkdir SECONDARY
#	set -x
	if [ "$mapfile" == "1" -a "$scans" != "ALL" ]; then
		OLDIFS=$IFS
		IFS=','
		sarr=( $scans )
		IFS=$OLDIFS
		echo save_UID_map $slabel `pwd`/scans.txt "${sarr[*]}"
		save_UID_map $slabel `pwd`/scans.txt "${sarr[*]}"
	fi
#	set +x
	mv */scans/*/*/$dcmdir/files/* DICOM/
	
	if (( uncompress )); then 
		echo uncompress_dcm_dir `pwd`/DICOM
		uncompress_dcm_dir `pwd`/DICOM
	fi 
	if (( rm_enh )); then 
		echo dcm_rm_enh  DICOM
		dcm_rm_enh DICOM
	fi
	$dcmsrt DICOM &> /dev/null
	if (( $? )); then exit_with_error "dcm_sort failed"; fi

	rm -r $slabel
	#mv */scans/*/*/secondary/files/* SECONDARY
	#dcm_sort DICOM
else
	echo $prms "${server}/REST/projects/${project}/subjects/${subj}/experiments/${slabel}/resources/${rdirs}/files?format=zip"
	$prm "${server}/REST/projects/${project}/subjects/${subj}/experiments/${slabel}/resources/${rdirs}/files?format=zip" > temp.zip
	unzip temp.zip &> /dev/null
	if (( $? )); then exit_with_error "unzip failed"; fi
	rm temp.zip
	mv ${slabel}/resources/* .
	lst=( `split_str $rdirs ","` )
	for ((i=0; i<${#lst[*]}; i++)); do
		t=${lst[i]}
		mv $t/files/* $t/
		rm -r $t/files
	done
fi

popd &> /dev/null

