#!/bin/bash

echo "Upload a directory with numbered DICOM scans to an XNAT experiment"
if [ -z $2 ]; then
	echo "Usage: scans2xnat <session label> <local directory> [options]"
	echo "e.g. scans2xnat SUBJ1_MRSESSION1 ProcessedDir -u user -pa password -sr myXNAT -pr MYPROJ -subj SUBJ1"
	echo "Options:"
	echo "	-sr	<server>			"
	echo "	-u	<user>"
	echo "	-pa	<password>"
	echo "	-js	<JSESSION>"
	echo "	-pr	<XNAT project>"
	echo "	-subj	<subject ID>"
	exit -1
fi

slabel=$1; shift
dir=$1; shift


while [ -n "$1" ]; do
    case $1 in 
        -sr)    shift; server=$1; shift ;;
        -u)     shift; user=$1; shift ;;
        -pa)    shift; pass=$1; shift ;;
		-js)	shift; JSESSION=$1; shift ;;
        -pr)    shift; project=$1; shift ;;
        -subj)  shift; subj=$1; shift ;;
            *)  shift ;;
    esac
done

echo "verifying login..."
if [ -z "$JSESSION" ]; then
	JSESSION=`curl -s -k -u $user:$pass "$server/data/JSESSION"`
	JSERROR=`echo $JSESSION | grep Error`
fi
if [ -n "$JSERROR" ]; then	echo "scans2xnat ERROR: cannot acquire JSESSION"; exit -1; fi	

#zip and upload each scan.
pushd $dir
    for d in `ls -d *`; do
	    if [ ! -d "$d" ]; then continue; fi
	    echo loc2xnat $slabel $d d -sr $server -js $JSESSION -pr $project -subj $subj -s $d -d
	    loc2xnat $slabel $d d -sr $server -js $JSESSION -pr $project -subj $subj -s $d -d
	    if  (( $? )); then
	        echo "loc2xnat failed, re-trying"
		loc2xnat $slabel $d d -sr $server -js $JSESSION -pr $project -subj $subj -s $d -d
	        if (( $? )); then echo "loc2xnat re-try failed"; exit -1; fi
	    fi	    
    done
popd

echo curl -k --cookie JSESSIONID=$JSESSION -X PUT $server/data/archive/projects/$project/subjects/$subj/experiments/$slabel?pullDataFromHeaders=true
curl -k --cookie JSESSIONID=$JSESSION -X PUT $server/data/archive/projects/$project/subjects/$subj/experiments/$slabel?pullDataFromHeaders=true

if (( $? )); then
    echo "request to regenerate metadata failed, re-trying"
    curl -k --cookie JSESSIONID=$JSESSION -X PUT $server/data/archive/projects/$project/subjects/$subj/experiments/$slabel?pullDataFromHeaders=true
    if (( $? )); then
	echo "re-try failed"
	exit -1
    fi
fi

